/* eslint-disable */
// AUTO-GENERATED by scripts/generate-pii-patterns.mjs from
// pii-patterns/default.yaml. DO NOT EDIT BY HAND.
//
// Y04 — embed the canonical 14 PII regex patterns at build time. Mirrors
// the Rust `include_str!` adoption in crates/agentum-dlp/src/detector.rs.
// Y09 (parity gate) will hash this file's source YAML and fail CI on drift.

export interface EmbeddedPattern {
  readonly id: string;
  readonly label: string;
  readonly severity: "low" | "medium" | "high" | "critical";
  readonly description: string;
  /** PCRE-derived source, with PCRE inline flags translated to JS `flags`. */
  readonly regexSource: string;
  /** JS RegExp flags (always includes `g` so iterative replace works). */
  readonly regexFlags: string;
}

export const PII_PATTERNS_YAML_VERSION = 1;

/**
 * Y09 — sha256 of the raw `pii-patterns/default.yaml` bytes the generator
 * consumed. The CI hash-check script (`scripts/check-pii-yaml-hash.sh`)
 * diffs this constant against a fresh `shasum -a 256` of the YAML on disk
 * and fails the build if they differ, catching the "edited YAML but forgot
 * to re-run `npm run prebuild`" footgun before parity tests even run.
 */
export const yamlSourceHash = "7cc481429288e16db6f62922139d626e4fff0a70c507d4782e6997e738146b20";

export const DEFAULT_PATTERNS: readonly EmbeddedPattern[] = [
  {
    "id": "email",
    "label": "Email address",
    "severity": "medium",
    "description": "RFC 5322-ish email shape, case-insensitive, intentionally lax.",
    "regexSource": "\\b[a-z0-9._%+\\-]+@[a-z0-9.\\-]+\\.[a-z]{2,}\\b",
    "regexFlags": "gi"
  },
  {
    "id": "phone_us",
    "label": "US phone number (NANP)",
    "severity": "medium",
    "description": "NANP shape. Skips loose 10-digit runs to avoid timestamps/IDs.",
    "regexSource": "\\b(?:\\+?1[\\s\\-.]?)?\\(?([2-9][0-8][0-9])\\)?[\\s\\-.]?([2-9][0-9]{2})[\\s\\-.]?([0-9]{4})\\b",
    "regexFlags": "g"
  },
  {
    "id": "ssn_us",
    "label": "US Social Security Number",
    "severity": "high",
    "description": "Candidate shape. Rust pairs with SSA validity rules (area != 000/666/9xx; group != 00; serial != 0000).",
    "regexSource": "\\b(\\d{3})[\\s\\-]?(\\d{2})[\\s\\-]?(\\d{4})\\b",
    "regexFlags": "g"
  },
  {
    "id": "credit_card",
    "label": "Credit card number",
    "severity": "high",
    "description": "13–19 digit run with optional spaces/hyphens. Rust pairs with a Luhn check.",
    "regexSource": "\\b(?:\\d[ \\-]?){12,18}\\d\\b",
    "regexFlags": "g"
  },
  {
    "id": "ip_address",
    "label": "IPv4 address",
    "severity": "medium",
    "description": "IPv4. Includes private ranges by design.",
    "regexSource": "\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b",
    "regexFlags": "g"
  },
  {
    "id": "aws_access_key_id",
    "label": "AWS access key ID",
    "severity": "critical",
    "description": "AKIA (long-term) and ASIA (STS) prefixes.",
    "regexSource": "\\b(?:AKIA|ASIA)[0-9A-Z]{16}\\b",
    "regexFlags": "g"
  },
  {
    "id": "aws_secret_access_key",
    "label": "AWS secret access key",
    "severity": "critical",
    "description": "Anchored on the key= prefix to avoid firing on any 40-char base64-ish run.",
    "regexSource": "aws_secret_access_key[\\s]*[:=][\\s]*[A-Za-z0-9/+=]{40}",
    "regexFlags": "gi"
  },
  {
    "id": "github_token",
    "label": "GitHub token",
    "severity": "critical",
    "description": "Classic PAT, fine-grained, app, user-to-server, refresh, OAuth tokens.",
    "regexSource": "\\bgh[pousr]_[A-Za-z0-9]{36,255}\\b",
    "regexFlags": "g"
  },
  {
    "id": "slack_token",
    "label": "Slack token",
    "severity": "critical",
    "description": "",
    "regexSource": "\\bxox[baprs]-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24,34}\\b",
    "regexFlags": "g"
  },
  {
    "id": "openai_key",
    "label": "OpenAI API key",
    "severity": "critical",
    "description": "Classic sk- and newer sk-proj- project-scoped keys.",
    "regexSource": "\\bsk-(?:proj-)?[A-Za-z0-9_\\-]{20,}\\b",
    "regexFlags": "g"
  },
  {
    "id": "anthropic_key",
    "label": "Anthropic API key",
    "severity": "critical",
    "description": "",
    "regexSource": "\\bsk-ant-api\\d{2}-[A-Za-z0-9_\\-]{90,}\\b",
    "regexFlags": "g"
  },
  {
    "id": "google_api_key",
    "label": "Google API key",
    "severity": "critical",
    "description": "",
    "regexSource": "\\bAIza[0-9A-Za-z_\\-]{35}\\b",
    "regexFlags": "g"
  },
  {
    "id": "jwt_token",
    "label": "JWT",
    "severity": "critical",
    "description": "Three base64url-ish segments separated by dots, starting with the {\"alg\":... header prefix.",
    "regexSource": "\\beyJ[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\.[A-Za-z0-9_\\-]{10,}\\b",
    "regexFlags": "g"
  },
  {
    "id": "private_key_pem",
    "label": "PEM private key",
    "severity": "critical",
    "description": "PEM header line only. Redaction handler extends to the full BEGIN/END block.",
    "regexSource": "-----BEGIN (?:RSA |EC |DSA |OPENSSH |ENCRYPTED |PGP )?PRIVATE KEY-----",
    "regexFlags": "g"
  },
  {
    "id": "bearer_token",
    "label": "HTTP Bearer token",
    "severity": "critical",
    "description": "Authorization: Bearer <token> shape. Long enough (>=20 chars after the keyword) to skip common test fixtures while catching real JWTs and opaque tokens. NOTE: jwt_token fires first on most JWTs; this catches non-JWT bearers.\n",
    "regexSource": "\\bBearer\\s+[A-Za-z0-9\\-._~+/]{20,}\\b",
    "regexFlags": "gi"
  },
  {
    "id": "generic_high_entropy",
    "label": "Generic high-entropy secret",
    "severity": "critical",
    "description": "40-char base64 run (>=40 chars before optional padding) as a coarse heuristic for high-entropy opaque secrets. High false-positive risk on long identifiers and binary blobs - kept at 40 chars minimum to reduce noise. Operators with high-FP environments may disable via AGENTUM__DLP_BLOCK_KINDS exclusion or a custom Detector build.\n",
    "regexSource": "[A-Za-z0-9+/]{40,}={0,2}",
    "regexFlags": "g"
  }
] as const;
